const root = document.getElementById('film');
document.documentElement.style.fontSize = `${Math.min(Number(root.dataset.width), Number(root.dataset.height)) / 67.5}px`;
const tl = gsap.timeline({ paused: true });
tl.fromTo('.hook .word', { y: 55, opacity: 1 }, { y: 0, opacity: 1, duration: 0.6, stagger: 0.18, ease: 'power3.out' }, 0);
tl.fromTo('.intro', { y: 25, opacity: 0 }, { y: 0, opacity: 1, duration: 0.5 }, 0.65);
tl.fromTo('.hook-mark span', { scaleY: 0 }, { scaleY: 1, stagger: 0.15, duration: 0.7, ease: 'back.out(1.2)' }, 0.4);
tl.to('.hook-mark span', { scaleY: 0.55, stagger: 0.12, duration: 0.35, yoyo: true, repeat: 3, ease: 'sine.inOut' }, 1.2);
tl.fromTo('.build h1 span', { x: -70, opacity: 0.65 }, { x: 0, opacity: 1, duration: 0.5, stagger: 0.14, ease: 'power3.out' }, 3);
tl.fromTo('.file', { y: 80, rotation: 5, opacity: 0 }, { y: 0, rotation: 0, opacity: 1, duration: 0.65, stagger: 0.3, ease: 'power3.out' }, 3.25);
tl.fromTo('.rule', { scaleX: 0 }, { scaleX: 1, transformOrigin: 'left', duration: 0.5, stagger: 0.1 }, 3.9);
tl.fromTo('.playhead', { x: 0 }, { x: document.querySelector('.timeline').getBoundingClientRect().width - 2, duration: 2, ease: 'none' }, 4.3);
tl.fromTo('.review h1 span', { y: 24 }, { y: 0, duration: 0.25, stagger: 0.12, ease: 'power3.out' }, 6.5);
tl.fromTo('.frame', { y: 100, rotation: -4, opacity: 0 }, { y: 0, rotation: 0, opacity: 1, duration: 0.65, stagger: 0.14, ease: 'power3.out' }, 6.85);
tl.fromTo('.word-mini', { scale: 0.6 }, { scale: 1, duration: 0.7, ease: 'power3.out' }, 7.1);
tl.fromTo('.shapes i', { scaleY: 0.35 }, { scaleY: 1, duration: 0.45, stagger: 0.15, yoyo: true, repeat: 3, ease: 'sine.inOut' }, 7.5);
tl.fromTo('.bars i', { scaleY: 0.35 }, { scaleY: 1, duration: 0.25, stagger: 0.06, yoyo: true, repeat: 7, ease: 'sine.inOut' }, 7.4);
tl.fromTo('.review-note', { opacity: 0, y: 20 }, { opacity: 1, y: 0, duration: 0.4 }, 7.65);
tl.fromTo('.format', { scale: 0.6, rotation: -10, opacity: 1 }, { scale: 1, rotation: 0, opacity: 1, duration: 0.7, stagger: 0.16, ease: 'power3.out' }, 10.5);
tl.to('.format-pair', { scale: 0.75, opacity: 0, duration: 0.4, ease: 'power2.in' }, 11.9);
tl.fromTo('.lockup', { y: 60, opacity: 0 }, { y: 0, opacity: 1, duration: 0.6, ease: 'power3.out' }, 12.2);
tl.fromTo('.lockup > img', { rotation: -8, scale: 0.8 }, { rotation: 0, scale: 1, duration: 0.7, ease: 'back.out(1.1)' }, 12.2);
tl.fromTo('.lockup p', { opacity: 0, y: 10 }, { opacity: 1, y: 0, duration: 0.45 }, 12.9);
window.__timelines = window.__timelines || {};
window.__timelines['motion-mania'] = tl;
